const {
  MONGO_HOST_1,
  MONGO_HOST_2,
  MONGO_HOST_3,
  MONGO_PORT,
  MONGO_DATABASE_MONITORED,
  MONGO_COLLECTIONS_MONITORED,
} = process.env;

module.exports = {
  MONGO_URI_MONITORED_DB: `mongodb://${MONGO_HOST_1}:${MONGO_PORT},${MONGO_HOST_2}:${MONGO_PORT},${MONGO_HOST_3}:${MONGO_PORT}/${MONGO_DATABASE_MONITORED}?replicaSet=devrs`,
  MONGO_DATABASE_MONITORED,
  MONGO_COLLECTIONS_MONITORED: MONGO_COLLECTIONS_MONITORED.split(' '),
};
