version: '3'

services:
  mongodb-sd:
    image: mongo:latest
    container_name: mongodb-sd
    restart: always
    volumes:
      - mongodb-sd:/data/db
    ports:
      - '${MONGO_PUBLIC_PORT}:${MONGO_PORT}'
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'devrs']

  mongo-r1:
    hostname: mongo-r1
    container_name: mongo-r1
    image: mongo
    volumes:
      - mongo-r1:/data/db

    expose:
      - 27017
    ports:
      - 30001:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'devrs']
    environment:
      - TZ=Asia/Ho_Chi_Minh

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - '/Users/manhhust/Desktop/changestream-service:/app'
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MONGO_HOST_ORIGINAL=${MONGO_HOST_ORIGINAL}
      - MONGO_HOST_R1=${MONGO_HOST_R1}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE_MONITORED=${MONGO_DATABASE_MONITORED}
      - MONGO_COLLECTIONS_MONITORED=${MONGO_COLLECTIONS_MONITORED}
      - GATEWAY_HOST=${GATEWAY_HOST}
      - GATEWAY_PORT=${GATEWAY_PORT}
    depends_on:
      - mongodb-sd
      - mongo-r1

volumes:
  mongodb-sd:
  mongo-r1:
networks:
  default:
    external:
      name: gateway_default
